In [2]:
#Pandas
import pandas as pd

In [5]:
#Path analysis
import os
cwd = os.getcwd()
cwd

'g:\\Mi unidad\\Data Science\\Kaggle Game Prediction\\kaggle_student_prediction\\notebooks'

In [6]:
#First insight of data
df=pd.read_csv("../data/raw/train.csv")
df.head()

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,NaN,NaN,NaN,0-4
1,20090312431273200,1,1323,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,NaN,NaN,NaN,0-4
2,20090312431273200,2,831,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,NaN,NaN,NaN,0-4
3,20090312431273200,3,1147,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,NaN,NaN,NaN,0-4
4,20090312431273200,4,1863,person_click,basic,0,NaN,-412.991405,-159.314686,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,NaN,NaN,NaN,0-4

In [8]:
#First transform
df.to_parquet('output.parquet')

In [10]:
#Memory usage
df.memory_usage()

Index                   128
session_id        105393688
index             105393688
elapsed_time      105393688
event_name        105393688
name              105393688
level             105393688
page              105393688
room_coor_x       105393688
room_coor_y       105393688
screen_coor_x     105393688
screen_coor_y     105393688
hover_duration    105393688
text              105393688
fqid              105393688
room_fqid         105393688
text_fqid         105393688
fullscreen        105393688
hq                105393688
music             105393688
level_group       105393688
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13174211 entries, 0 to 13174210
Data columns (total 20 columns):
 #   Column          Dtype
---  ------          -----
 0   session_id      int64
 1   index           int64
 2   elapsed_time    int64
 3   event_name      object
 4   name            object
 5   level           int64
 6   page            float64
 7   room_coor_x     float64
 8   room_coor_y     float64
 9   screen_coor_x   float64
 10  screen_coor_y   float64
 11  hover_duration  float64
 12  text            object
 13  fqid            object
 14  room_fqid       object
 15  text_fqid       object
 16  fullscreen      float64
 17  hq              float64
 18  music           float64
 19  level_group     object
dtypes: float64(9), int64(4), object(7)
memory usage: 2.0+ GB

In [12]:
#https://towardsdatascience.com/how-to-reduce-the-size-of-a-pandas-dataframe-in-python-7ed6e4269f88
## downcasting loop
for column in df:
 if df[column].dtype == "float64":
    df[column]=pd.to_numeric(df[column], downcast="float")
 if df[column].dtype == "int64":
    df[column]=pd.to_numeric(df[column], downcast="integer")

In [13]:
df.memory_usage()

Index                   128
session_id        105393688
index              26348422
elapsed_time       52696844
event_name        105393688
name              105393688
level              13174211
page               52696844
room_coor_x        52696844
room_coor_y        52696844
screen_coor_x      52696844
screen_coor_y      52696844
hover_duration    105393688
text              105393688
fqid              105393688
room_fqid         105393688
text_fqid         105393688
fullscreen         52696844
hq                 52696844
music              52696844
level_group       105393688
dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13174211 entries, 0 to 13174210
Data columns (total 20 columns):
 #   Column          Dtype
---  ------          -----
 0   session_id      int64
 1   index           int16
 2   elapsed_time    int32
 3   event_name      object
 4   name            object
 5   level           int8
 6   page            float32
 7   room_coor_x     float32
 8   room_coor_y     float32
 9   screen_coor_x   float32
 10  screen_coor_y   float32
 11  hover_duration  float64
 12  text            object
 13  fqid            object
 14  room_fqid       object
 15  text_fqid       object
 16  fullscreen      float32
 17  hq              float32
 18  music           float32
 19  level_group     object
dtypes: float32(8), float64(1), int16(1), int32(1), int64(1), int8(1), object(7)
memory usage: 1.4+ GB

In [15]:
del df

In [16]:
df2=pd.read_parquet("output.parquet")

In [17]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13174211 entries, 0 to 13174210
Data columns (total 20 columns):
 #   Column          Dtype
---  ------          -----
 0   session_id      int64
 1   index           int64
 2   elapsed_time    int64
 3   event_name      object
 4   name            object
 5   level           int64
 6   page            float64
 7   room_coor_x     float64
 8   room_coor_y     float64
 9   screen_coor_x   float64
 10  screen_coor_y   float64
 11  hover_duration  float64
 12  text            object
 13  fqid            object
 14  room_fqid       object
 15  text_fqid       object
 16  fullscreen      float64
 17  hq              float64
 18  music           float64
 19  level_group     object
dtypes: float64(9), int64(4), object(7)
memory usage: 2.0+ GB

In [18]:
df2.memory_usage()

Index                   128
session_id        105393688
index             105393688
elapsed_time      105393688
event_name        105393688
name              105393688
level             105393688
page              105393688
room_coor_x       105393688
room_coor_y       105393688
screen_coor_x     105393688
screen_coor_y     105393688
hover_duration    105393688
text              105393688
fqid              105393688
room_fqid         105393688
text_fqid         105393688
fullscreen        105393688
hq                105393688
music             105393688
level_group       105393688
dtype: int64

In [19]:
df2.head()

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,NaN,NaN,NaN,0-4
1,20090312431273200,1,1323,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,NaN,NaN,NaN,0-4
2,20090312431273200,2,831,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,NaN,NaN,NaN,0-4
3,20090312431273200,3,1147,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,NaN,NaN,NaN,0-4
4,20090312431273200,4,1863,person_click,basic,0,NaN,-412.991405,-159.314686,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,NaN,NaN,NaN,0-4